# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alamofire MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Alamofire MVVM
  
  pod 'SnapKit'
  pod 'Alamofire'

end
